export interface TemplateLink {
  title: string
  url: string
  icon?: string
  section?: string
}

export interface TemplateSocial {
  platform: string
  handle: string
}

export interface TemplateAppearance {
  theme: string
  accentColor: string
  buttonStyle: string
  bioAlignment: string
  buttonTextColor?: string
  backgroundColor?: string
  avatarShape?: string
  fontFamily: string
  fontSize: string
  linkBorderWidth: string
  linkShadow: string
  linkSpacing: string
  layoutMode: string
  hoverEffect: string
  showAvatar?: boolean
  showBio?: boolean
  buttonFontWeight?: string
}

export interface Template {
  id: string
  name: string
  description: string
  category: string
  isPro?: boolean
  emoji: string
  previewGradient: string
  previewAccent: string
  appearance: TemplateAppearance
  links: TemplateLink[]
  social: TemplateSocial[]
}

export const templates: Template[] = [
  {
    id: "creator",
    name: "Creator",
    description: "A clean, friendly starter for content creators and influencers",
    category: "Creator",
    emoji: "✨",
    previewGradient: "from-slate-50 to-white",
    previewAccent: "bg-indigo-500",
    appearance: {
      theme: "default",
      accentColor: "#6366f1",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Latest YouTube Video", url: "https://youtube.com/@yourname", icon: "▶️", section: "Featured" },
      { title: "My Store / Merch", url: "https://store.example.com", icon: "🛍️" },
      { title: "Join My Newsletter", url: "https://newsletter.example.com", icon: "📬" },
      { title: "Book a 1:1 Call", url: "https://cal.com/yourname", icon: "📅" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
    ],
  },
  {
    id: "photographer",
    name: "Photographer",
    description: "Minimal dark layout that lets your images do the talking",
    category: "Creative",
    emoji: "📷",
    previewGradient: "from-neutral-900 to-neutral-800",
    previewAccent: "bg-rose-500",
    appearance: {
      theme: "dark",
      accentColor: "#f43f5e",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "medium",
      linkSpacing: "comfortable",
      layoutMode: "grid",
      hoverEffect: "scale",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Portfolio", url: "https://portfolio.example.com", icon: "🖼️", section: "Work" },
      { title: "Book a Session", url: "https://cal.com/yourname", icon: "📸" },
      { title: "Prints Shop", url: "https://shop.example.com", icon: "🛒" },
      { title: "Lightroom Presets", url: "https://presets.example.com", icon: "🎨" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "pinterest", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
    ],
  },
  {
    id: "musician",
    name: "Musician",
    description: "Bold and energetic — built to push streams and drops",
    category: "Creative",
    emoji: "🎵",
    previewGradient: "from-violet-950 to-slate-900",
    previewAccent: "bg-fuchsia-500",
    isPro: true,
    appearance: {
      theme: "midnight",
      accentColor: "#d946ef",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "lg",
      linkBorderWidth: "thin",
      linkShadow: "large",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "glow",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Listen on Spotify", url: "https://open.spotify.com/artist/yourname", icon: "🎧", section: "Stream" },
      { title: "Apple Music", url: "https://music.apple.com/artist/yourname", icon: "🍎" },
      { title: "New Music Video", url: "https://youtube.com/@yourname", icon: "🎬" },
      { title: "Tour Dates", url: "https://tour.example.com", icon: "🎤" },
      { title: "Buy Vinyl", url: "https://store.example.com", icon: "💿" },
    ],
    social: [
      { platform: "spotify", handle: "yourname" },
      { platform: "instagram", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
    ],
  },
  {
    id: "developer",
    name: "Developer",
    description: "Sharp monospace style for builders and indie hackers",
    category: "Tech",
    emoji: "💻",
    previewGradient: "from-slate-900 to-slate-800",
    previewAccent: "bg-emerald-500",
    isPro: true,
    appearance: {
      theme: "midnight",
      accentColor: "#10b981",
      buttonStyle: "square",
      bioAlignment: "left",
      fontFamily: "mono",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "none",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "slide",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "GitHub", url: "https://github.com/yourname", icon: "🐙", section: "Code" },
      { title: "Live Demo", url: "https://demo.example.com", icon: "🚀" },
      { title: "Read My Blog", url: "https://blog.example.com", icon: "📝" },
      { title: "Hire Me", url: "mailto:you@example.com", icon: "💼" },
    ],
    social: [
      { platform: "github", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
      { platform: "linkedin", handle: "yourname" },
    ],
  },
  {
    id: "business",
    name: "Business",
    description: "Professional and trustworthy for brands and services",
    category: "Business",
    emoji: "💼",
    previewGradient: "from-blue-50 to-cyan-50",
    previewAccent: "bg-blue-600",
    appearance: {
      theme: "ocean",
      accentColor: "#2563eb",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "sora",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Our Website", url: "https://example.com", icon: "🌐", section: "Company" },
      { title: "Book a Demo", url: "https://cal.com/yourname", icon: "📅" },
      { title: "Customer Support", url: "mailto:support@example.com", icon: "💬" },
      { title: "Careers", url: "https://example.com/careers", icon: "🧑‍💼" },
    ],
    social: [
      { platform: "linkedin", handle: "yourcompany" },
      { platform: "twitter", handle: "yourcompany" },
      { platform: "facebook", handle: "yourcompany" },
    ],
  },
  {
    id: "fitness",
    name: "Coach & Fitness",
    description: "Energetic and motivating for trainers and coaches",
    category: "Lifestyle",
    emoji: "💪",
    previewGradient: "from-orange-100 to-rose-100",
    previewAccent: "bg-orange-500",
    appearance: {
      theme: "sunset",
      accentColor: "#f97316",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "medium",
      linkSpacing: "comfortable",
      layoutMode: "list",
      hoverEffect: "scale",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Free Trial Workout", url: "https://example.com/trial", icon: "🔥", section: "Train" },
      { title: "Coaching Plans", url: "https://example.com/plans", icon: "📋" },
      { title: "YouTube Channel", url: "https://youtube.com/@yourname", icon: "🎥" },
      { title: "Meal Guide", url: "https://example.com/guide", icon: "🥗" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
    ],
  },
  {
    id: "restaurant",
    name: "Restaurant",
    description: "Warm and appetizing layout for menus and reservations",
    category: "Business",
    emoji: "🍽️",
    previewGradient: "from-amber-100 to-orange-100",
    previewAccent: "bg-amber-600",
    appearance: {
      theme: "autumn",
      accentColor: "#d97706",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "View Menu", url: "https://example.com/menu", icon: "📖", section: "Visit" },
      { title: "Reservations", url: "https://resy.com/yourname", icon: "📅" },
      { title: "Order Delivery", url: "https://example.com/order", icon: "🛵" },
      { title: "Hours & Location", url: "https://maps.google.com/?q=yourname", icon: "📍" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "facebook", handle: "yourname" },
    ],
  },
  {
    id: "author",
    name: "Author & Writer",
    description: "Elegant typography-focused layout for writers",
    category: "Creative",
    emoji: "📚",
    previewGradient: "from-violet-100 to-purple-100",
    previewAccent: "bg-violet-600",
    isPro: true,
    appearance: {
      theme: "lavender",
      accentColor: "#8b5cf6",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "medium",
      linkSpacing: "comfortable",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Buy My Book", url: "https://amazon.com/author/yourname", icon: "📕", section: "Books" },
      { title: "Read the Blog", url: "https://blog.example.com", icon: "✍️" },
      { title: "Newsletter", url: "https://newsletter.example.com", icon: "📰" },
      { title: "Speaking Events", url: "https://example.com/events", icon: "🎤" },
    ],
    social: [
      { platform: "twitter", handle: "yourname" },
      { platform: "instagram", handle: "yourname" },
      { platform: "linkedin", handle: "yourname" },
    ],
  },
  {
    id: "podcaster",
    name: "Podcaster",
    description: "Punchy layout to grow listeners across platforms",
    category: "Media",
    emoji: "🎙️",
    previewGradient: "from-indigo-950 to-slate-900",
    previewAccent: "bg-cyan-500",
    isPro: true,
    appearance: {
      theme: "midnight",
      accentColor: "#06b6d4",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "medium",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "glow",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Listen on Spotify", url: "https://open.spotify.com/show/yourname", icon: "🎧", section: "Listen" },
      { title: "Apple Podcasts", url: "https://podcasts.apple.com/yourname", icon: "🍎" },
      { title: "Latest Episode", url: "https://youtube.com/@yourname", icon: "🎬" },
      { title: "Support on Patreon", url: "https://patreon.com/yourname", icon: "💜" },
    ],
    social: [
      { platform: "youtube", handle: "yourname" },
      { platform: "instagram", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
    ],
  },
  {
    id: "student",
    name: "Student & Portfolio",
    description: "Simple and bright for students and job seekers",
    category: "Personal",
    emoji: "🎓",
    previewGradient: "from-emerald-100 to-teal-100",
    previewAccent: "bg-teal-600",
    appearance: {
      theme: "mint",
      accentColor: "#14b8a6",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Resume / CV", url: "https://example.com/resume", icon: "📄", section: "Me" },
      { title: "LinkedIn", url: "https://linkedin.com/in/yourname", icon: "💼" },
      { title: "Projects", url: "https://github.com/yourname", icon: "🚀" },
      { title: "Contact Me", url: "mailto:you@example.com", icon: "✉️" },
    ],
    social: [
      { platform: "linkedin", handle: "yourname" },
      { platform: "github", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate",
    description: "Trust-building layout for agents and listings",
    category: "Business",
    emoji: "🏠",
    previewGradient: "from-blue-50 to-indigo-50",
    previewAccent: "bg-blue-700",
    appearance: {
      theme: "ocean",
      accentColor: "#1d4ed8",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "sora",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Browse Listings", url: "https://example.com/listings", icon: "🔑", section: "Listings" },
      { title: "Book a Viewing", url: "https://cal.com/yourname", icon: "📅" },
      { title: "Free Home Valuation", url: "https://example.com/valuation", icon: "📊" },
      { title: "Client Reviews", url: "https://example.com/reviews", icon: "⭐" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "facebook", handle: "yourname" },
      { platform: "linkedin", handle: "yourname" },
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Salon",
    description: "Soft and stylish for salons, artists and creators",
    category: "Lifestyle",
    emoji: "💄",
    previewGradient: "from-rose-50 to-pink-50",
    previewAccent: "bg-pink-500",
    appearance: {
      theme: "coral",
      accentColor: "#ec4899",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "comfortable",
      layoutMode: "grid",
      hoverEffect: "scale",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Book Appointment", url: "https://book.example.com", icon: "💇", section: "Book" },
      { title: "Portfolio", url: "https://instagram.com/yourname", icon: "📸" },
      { title: "Shop Products", url: "https://shop.example.com", icon: "🛍️" },
      { title: "Gift Cards", url: "https://example.com/gift", icon: "🎁" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "facebook", handle: "yourname" },
    ],
  },
  {
    id: "gamer",
    name: "Gamer & Streamer",
    description: "Neon-on-dark look built for streams and esports",
    category: "Gaming",
    emoji: "🎮",
    previewGradient: "from-indigo-950 to-slate-900",
    previewAccent: "bg-lime-400",
    isPro: true,
    appearance: {
      theme: "midnight",
      accentColor: "#a3e635",
      buttonStyle: "square",
      bioAlignment: "center",
      fontFamily: "mono",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "large",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "glow",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Twitch Stream", url: "https://twitch.tv/yourname", icon: "🎥", section: "Watch" },
      { title: "YouTube", url: "https://youtube.com/@yourname", icon: "▶️" },
      { title: "My Discord", url: "https://discord.gg/yourname", icon: "💬" },
      { title: "Merch Store", url: "https://store.example.com", icon: "🛍️" },
    ],
    social: [
      { platform: "twitch", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "discord", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Lifestyle",
    description: "Bright, airy style for wanderlusters and bloggers",
    category: "Lifestyle",
    emoji: "✈️",
    previewGradient: "from-sky-100 to-cyan-100",
    previewAccent: "bg-sky-500",
    appearance: {
      theme: "ocean",
      accentColor: "#0ea5e9",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "sora",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "comfortable",
      layoutMode: "grid",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Latest Travel Guide", url: "https://blog.example.com", icon: "🧳", section: "Explore" },
      { title: "My YouTube Vlogs", url: "https://youtube.com/@yourname", icon: "🎬" },
      { title: "Photo Prints", url: "https://shop.example.com", icon: "🖼️" },
      { title: "Travel Newsletter", url: "https://newsletter.example.com", icon: "📬" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "pinterest", handle: "yourname" },
    ],
  },
  {
    id: "wedding",
    name: "Wedding & Event",
    description: "Soft and romantic for weddings and special days",
    category: "Personal",
    emoji: "💍",
    previewGradient: "from-rose-100 to-pink-100",
    previewAccent: "bg-rose-400",
    appearance: {
      theme: "coral",
      accentColor: "#db2777",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "comfortable",
      layoutMode: "list",
      hoverEffect: "scale",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Our Story", url: "https://example.com/story", icon: "📖", section: "Event" },
      { title: "RSVP", url: "https://example.com/rsvp", icon: "💌" },
      { title: "Registry", url: "https://example.com/registry", icon: "🎁" },
      { title: "Venue & Directions", url: "https://maps.google.com/?q=venue", icon: "📍" },
    ],
    social: [
      { platform: "instagram", handle: "yourcouple" },
      { platform: "facebook", handle: "yourcouple" },
    ],
  },
  {
    id: "foodie",
    name: "Food & Recipe",
    description: "Warm, appetizing style for cooks and foodies",
    category: "Lifestyle",
    emoji: "🍳",
    previewGradient: "from-amber-100 to-orange-100",
    previewAccent: "bg-orange-500",
    appearance: {
      theme: "autumn",
      accentColor: "#ea580c",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Latest Recipe", url: "https://blog.example.com", icon: "🥘", section: "Cook" },
      { title: "YouTube Channel", url: "https://youtube.com/@yourname", icon: "🎥" },
      { title: "Cookbook", url: "https://shop.example.com", icon: "📕" },
      { title: "Meal Plan", url: "https://example.com/plan", icon: "📋" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "pinterest", handle: "yourname" },
    ],
  },
  {
    id: "fashion",
    name: "Fashion & Style",
    description: "Chic editorial layout for fashion creators",
    category: "Creative",
    emoji: "👗",
    previewGradient: "from-violet-100 to-purple-100",
    previewAccent: "bg-purple-500",
    isPro: true,
    appearance: {
      theme: "lavender",
      accentColor: "#a855f7",
      buttonStyle: "pill",
      bioAlignment: "center",
      fontFamily: "serif",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "medium",
      linkSpacing: "comfortable",
      layoutMode: "grid",
      hoverEffect: "scale",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Shop My Closet", url: "https://shop.example.com", icon: "🛍️", section: "Style" },
      { title: "Latest Lookbook", url: "https://instagram.com/yourname", icon: "📸" },
      { title: "Get the Look", url: "https://blog.example.com", icon: "✨" },
      { title: "Collaborate", url: "mailto:you@example.com", icon: "💼" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
      { platform: "pinterest", handle: "yourname" },
    ],
  },
  {
    id: "wellness",
    name: "Health & Wellness",
    description: "Calm, grounding layout for coaches and yogis",
    category: "Lifestyle",
    emoji: "🧘",
    previewGradient: "from-emerald-100 to-teal-100",
    previewAccent: "bg-emerald-500",
    appearance: {
      theme: "mint",
      accentColor: "#059669",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "modern",
      fontSize: "md",
      linkBorderWidth: "none",
      linkShadow: "subtle",
      linkSpacing: "comfortable",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "medium",
    },
    links: [
      { title: "Book a Session", url: "https://cal.com/yourname", icon: "📅", section: "Heal" },
      { title: "Free Meditation", url: "https://example.com/calm", icon: "🌿" },
      { title: "YouTube Channel", url: "https://youtube.com/@yourname", icon: "🎥" },
      { title: "Wellness Shop", url: "https://shop.example.com", icon: "🛒" },
    ],
    social: [
      { platform: "instagram", handle: "yourname" },
      { platform: "youtube", handle: "yourname" },
      { platform: "tiktok", handle: "yourname" },
    ],
  },
  {
    id: "nonprofit",
    name: "Nonprofit & Cause",
    description: "Trustworthy, mission-driven layout for causes",
    category: "Business",
    emoji: "🤝",
    previewGradient: "from-green-100 to-emerald-100",
    previewAccent: "bg-green-600",
    appearance: {
      theme: "mint",
      accentColor: "#16a34a",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "sora",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Donate Now", url: "https://example.com/donate", icon: "💚", section: "Support" },
      { title: "Our Mission", url: "https://example.com/mission", icon: "🌍" },
      { title: "Volunteer", url: "https://example.com/volunteer", icon: "🙌" },
      { title: "Latest Impact", url: "https://blog.example.com", icon: "📈" },
    ],
    social: [
      { platform: "instagram", handle: "yourorg" },
      { platform: "facebook", handle: "yourorg" },
      { platform: "linkedin", handle: "yourorg" },
    ],
  },
  {
    id: "consultant",
    name: "Consultant & Agency",
    description: "Sharp, professional layout to win clients",
    category: "Business",
    emoji: "📊",
    previewGradient: "from-blue-50 to-indigo-50",
    previewAccent: "bg-indigo-600",
    appearance: {
      theme: "ocean",
      accentColor: "#1e40af",
      buttonStyle: "rounded",
      bioAlignment: "center",
      fontFamily: "sora",
      fontSize: "md",
      linkBorderWidth: "thin",
      linkShadow: "subtle",
      linkSpacing: "normal",
      layoutMode: "list",
      hoverEffect: "lift",
      buttonFontWeight: "semibold",
    },
    links: [
      { title: "Book a Consultation", url: "https://cal.com/yourname", icon: "📅", section: "Work" },
      { title: "Case Studies", url: "https://example.com/work", icon: "📂" },
      { title: "Free Audit", url: "https://example.com/audit", icon: "🔍" },
      { title: "Contact Sales", url: "mailto:sales@example.com", icon: "💬" },
    ],
    social: [
      { platform: "linkedin", handle: "yourname" },
      { platform: "twitter", handle: "yourname" },
      { platform: "github", handle: "yourname" },
    ],
  },
]

export function getTemplate(id: string): Template | undefined {
  return templates.find((t) => t.id === id)
}
